server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/newDevps;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#    defer-datasource-initialization: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

jwt:
  secret: h2qRTFW0LM76tqMUf2RSInlD+D/VAaM5x6b9Y6hCCiU=

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace