### 추천장소 저장
POST http://localhost:8080/api/place
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkzMDI3MTYxLCJleHAiOjE2OTMwMjg5NjF9.O_44NbAvq_LJyVAPjgi9mt7iliEPPmRzVG2j4wn73R8
Content-Type: application/json

{
  "requestList" : [{
    "latitude" : 27.55,
    "longitude" : 42.56,
    "category" : "FOOD",
    "placeName" : "paris burger"
  },{
    "latitude" : 27.55,
    "longitude" : 42.56,
    "category" : "ACCOMMODATION",
    "placeName" : "nomad Accommodataion"
  }
  ]
}
