### 추천장소 저장
POST http://localhost:8080/api/place
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkzMjI3NTI4LCJleHAiOjE2OTMyMjkzMjh9.MgOIxxmWnQNKCMBkG_I8_HOmCe5Pyxgc1r_qhKZBNao
Content-Type: application/json

{
  "requestList" : [{
    "latitude" : 27.55,
    "longitude" : 42.56,
    "category" : "FOOD",
    "placeName" : "paris burger",
    "address" : "잠실 올림픽로 300 롯데타워 20층",
    "categoryName" : "카테고리 이름 > 식품 > 풀무원 > 순두부",
    "starRating" : 4.5
  },{
    "latitude" : 27.55,
    "longitude" : 42.56,
    "category" : "ACCOMMODATION",
    "placeName" : "nomad Accommodataion",
    "address" : "성수 서울숲 한가운데 노란 돗자리",
    "categoryName" : "카테고리 이름 > 닭 > 튀김 > 치킨",
    "starRating" : 2.0
  }
  ]
}
