### 게시글 저장
POST http://localhost:8080/api/post
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkyMzY1MDkzLCJleHAiOjE2OTIzNjY4OTN9.YwuWpWklIb3iUEIbeQM6FVX3MZWQW0LD7G1LTOGHEIg
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="content"

save Post
--boundary
Content-Disposition: form-data; name="placeName"

LA street 28-19
--boundary
Content-Disposition: form-data; name="dateTime"

2023-08-04
--boundary
Content-Disposition: form-data; name="latitude"

12.8892
--boundary
Content-Disposition: form-data; name="longitude"

49.7756
--boundary--

### 게시글 저장 2
POST http://localhost:8080/api/post
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkyMzY2ODM2LCJleHAiOjE2OTIzNjg2MzZ9.6UVjZeM1TkypwD1Uu7ecNZhp7RtP_d99fm7XkE4PY70
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="content"

save Post
--boundary
Content-Disposition: form-data; name="placeName"

LA street 28-19
--boundary
Content-Disposition: form-data; name="dateTime"

2023-08-04
--boundary
Content-Disposition: form-data; name="latitude"

12.8892
--boundary
Content-Disposition: form-data; name="longitude"

49.7756
--boundary
Content-Disposition: form-data; name="imageFiles"; filename="test.jpg";
Content-Type: image/gif

<D:\test.jpg
--boundary--

### 게시글 전체 조회
GET http://localhost:8080/api/post/all
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkyMzY1MDkzLCJleHAiOjE2OTIzNjY4OTN9.YwuWpWklIb3iUEIbeQM6FVX3MZWQW0LD7G1LTOGHEIg

### 게시글 단건 조회
GET http://localhost:8080/api/post/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkxNjc0ODYwLCJleHAiOjE2OTE2NzY2NjB9.lKFVLjoPbfU1Lj_neXgqpWN1beQwVrvFxmBjsKE0_-k

### 게시글 업데이트
PUT http://localhost:8080/api/post/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkxNjc0ODYwLCJleHAiOjE2OTE2NzY2NjB9.lKFVLjoPbfU1Lj_neXgqpWN1beQwVrvFxmBjsKE0_-k
Content-Type: application/json

{
  "content" : "내용을 수정하다",
  "placeName" : "도로명 주소 수정하다",
  "dateTime" : "2023-07-17",
  "latitude" : 12.8892,
  "longitude" : 49.77256
}

### 게시글 삭제
DELETE http://localhost:8080/api/post/1