### 게시글 저장
POST http://localhost:8080/api/post
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkzMDE4NjY5LCJleHAiOjE2OTMwMjA0Njl9.oqSjqD8vb0G_UAQu1vUy917oziNG_yj87SWW4AVraXI
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="content"

save Post
--boundary
Content-Disposition: form-data; name="placeName"

LA street 28-19
--boundary
Content-Disposition: form-data; name="dateTime"

2023-08-04
--boundary
Content-Disposition: form-data; name="latitude"

12.8892
--boundary
Content-Disposition: form-data; name="longitude"

49.7756
--boundary--

### 게시글 저장 2
POST http://localhost:8080/api/post
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkzMDI3MTYxLCJleHAiOjE2OTMwMjg5NjF9.O_44NbAvq_LJyVAPjgi9mt7iliEPPmRzVG2j4wn73R8
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="content"

save Post
--boundary
Content-Disposition: form-data; name="placeName"

LA street 28-19
--boundary
Content-Disposition: form-data; name="dateTime"

2023-08-04
--boundary
Content-Disposition: form-data; name="latitude"

12.8892
--boundary
Content-Disposition: form-data; name="longitude"

49.7756
--boundary
Content-Disposition: form-data; name="imageFiles"; filename="test.jpg";
Content-Type: image/gif

<D:\test.jpg
--boundary--

### 게시글 전체 조회
GET http://localhost:8080/api/post/all
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkzMDI2MTIwLCJleHAiOjE2OTMwMjc5MjB9.x0w5BzVG6mwOND13nfU6yW3fiKaBy31bTVGl9DoT9l4

### 게시글 단건 조회
GET http://localhost:8080/api/post/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkxNjc0ODYwLCJleHAiOjE2OTE2NzY2NjB9.lKFVLjoPbfU1Lj_neXgqpWN1beQwVrvFxmBjsKE0_-k

### 게시글 업데이트
PUT http://localhost:8080/api/post/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjkxNjc0ODYwLCJleHAiOjE2OTE2NzY2NjB9.lKFVLjoPbfU1Lj_neXgqpWN1beQwVrvFxmBjsKE0_-k
Content-Type: application/json

{
  "content" : "내용을 수정하다",
  "placeName" : "도로명 주소 수정하다",
  "dateTime" : "2023-07-17",
  "latitude" : 12.8892,
  "longitude" : 49.77256
}

### 게시글 삭제
DELETE http://localhost:8080/api/post/1